version: "3"
services:
  backend:
    image: erichall/uiuc-sentiment-backend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - sentiment_webnet

  frontend:
    image: erichall/uiucfrontend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - sentiment_webnet

networks:
  sentiment_webnet:
